project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
pull_request_title: Translation updates from Crowdin
pull_request_labels:
  - crowdin
commit_message: '[skip ci]'
files:
  - source: /test/test.loc
    translation: /translations/%two_letters_code%/test.loc
